directories:
  output: release
  buildResources: build
appId: com.mychat.app
productName: MyChat
win:
  target: nsis
  icon: public/icon.ico
files:
  - filter:
      - dist/**/*
      - src/main.js
      - src/preload.js
electronVersion: 33.4.11
